# Generated by Django 2.1.4 on 2018-12-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plans.Meal')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
