# Generated by Django 2.1.4 on 2018-12-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_foodchoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodchoices',
            old_name='text',
            new_name='meal_contents',
        ),
    ]
