# Generated by Django 2.1.4 on 2018-12-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_auto_20181206_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodchoices',
            options={'verbose_name_plural': 'meal contents'},
        ),
    ]
