# Generated by Django 2.1.4 on 2018-12-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_auto_20181206_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodchoices',
            old_name='meal_name',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='meal_name',
            new_name='text',
        ),
    ]
