# Generated by Django 2.1.4 on 2018-12-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0005_auto_20181206_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodchoices',
            old_name='meal_contents',
            new_name='text',
        ),
    ]
